name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: Europe/Paris
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15 
          plugin_languages_categories: programming  
          plugin_languages_recent_load: yes  

      - name: LeetCode
        uses: lowlighter/metrics@latest
        with:
          with:
            token: ${{ secrets.METRICS_TOKEN }}
            plugin_leetcode: yes
            plugin_leetcode_user: nassimch

